name: "WorkFlow for Django REST Framework Auto Test"

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/**
  workflow_dispatch:

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello World!!"
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/Script/activate
          pip install -r requirements.txt
