name: "WorkFlow for Django REST Framework Auto Test"

on:
  push:
    branches:
      - master
      - feature/github-workflow
    paths:
      - .github/workflows/**
  workflow_dispatch:

env:
  # TF_VERSION: 1.2.8

defaults:
  run:
    shell: bash
    # working-directory: "10_infra/"

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: "Print workflow url"
        run: |
          echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: "miura0617/django-drf-test"
      - name: "Upgrade pip"
        run: |
          python -m pip install --upgrade pip
      - name: "Setup python virtual environment phase1"
        run: |
          python -m venv venv
      - name: "Setup python virtual environment phase2"
        run: |
          source venv/Script/activate
      - name: "Install python packages"
        run: |
          pip install -r requirements.txt
